# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9c181300b5af9fd878679d9eaee8cd6c34a72e9479982dfe038f4b824d26969074b94ff950e6761be4f61cadc2336347b3dfdfe55666eb686edc86fc56f1e8d

test:
  secret_key_base: f87109acdef4d6e81c526e86d02172282fec3df743c6c692e8785330f671c41f6d064b4678e188987510d8ced1374806ffa0b7118e94655cb3e70dea92e87f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
